name: LaraBB-Build
on:
  pull_request:
    branches: [ main ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    services:
      mariadb:
        image: mariadb:10.6
        ports: ['3306:3306']
        env:
          MYSQL_ROOT_PASSWORD: test_db
          MYSQL_DATABASE: test_db
          MYSQL_USER: test_db
          MYSQL_PASSWORD: test_db
    steps:
      - uses: actions/checkout@v2

      - name: Install composer dependencies
        run: |
          composer install --no-scripts
      
      - name: Prepare Laravel Application
        run: |
          cp .env.ci .env
          php artisan key:generate
  
      - name: Run Test Suite
        run: vendor/bin/phpunit tests/